
import type { Metadata } from 'next'

import './globals.css'

import Navbar from './Navbar/Navbar'
import { Open_Sans } from 'next/font/google'

//👇 Configure our font object
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Akshat react',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body suppressHydrationWarning>
        <Navbar/>
        
        {children}</body>
    </html>
  )
}
