import type { Metadata } from 'next'

import './globals.css'
import HostelHead from './hostelheader/page'



export const metadata: Metadata = {
  title: 'Akshat react',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <HostelHead/>
        
        {children}</body>
    </html>
  )
}
